# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(660, 247)
        login.setStyleSheet("background-color: rgb(0, 0, 0)")




        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(190, 70, 261, 31))
        self.email.setStyleSheet("border: none;\n"
"border-bottom: 2px solid;\n"
"border-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(255, 255, 255)")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(190, 120, 261, 31))
        self.password.setStyleSheet("border: none;\n"
"border-bottom: 2px solid;\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.password.setObjectName("password")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(214, 170, 91, 31))
        self.btn_login.setStyleSheet("QWidget {\n"
"    margin-bottom: 3px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QWidget:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0)\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(330, 170, 81, 31))
        self.btn_register.setStyleSheet("QWidget {\n"
"    margin-bottom: 3px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QWidget:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0)\n"
"}")
        self.btn_register.setObjectName("btn_register")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 0, 321, 51))
        self.label.setStyleSheet("font: 14pt \"Arial Rounded MT Bold\";\n"
"color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "MainWindow"))
        self.email.setPlaceholderText(_translate("login", "Email"))
        self.password.setPlaceholderText(_translate("login", "password"))
        self.btn_login.setText(_translate("login", "Acceder"))
        self.btn_register.setText(_translate("login", "Registro"))
        self.label.setText(_translate("login", "CINEMAX COLOMBIA SAS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec())
